language: python
python: 2.6
install:
- pip install pep8 --use-mirrors
- pip install https://github.com/dcramer/pyflakes/tarball/master
script:
  - cd main
  - pep8 --exclude=migrations --ignore=E501,E225,E123 .
  - pyflakes -x W .
