default:
    proso_common:
        config:
          is_custom_config_allowed: true
    proso_models:
        random_test:
            nth: 10
        predictive_model:
            class: proso.models.prediction.PriorCurrentPredictiveModel
        option_selector:
            class: proso.models.option_selection.AdjustedOptionSelection
        options_count:
            class: proso.models.option_selection.AdjustedOptionsNumber
            parameters:
                allow_zero_options_restriction: true
        practice:
            common:
                set_length: 10
                fc_queue_size_max: 1
                fc_queue_size_min: 1
                save_answer_immediately: false
                cache_context: false
                queue_length: 10
        item_selector:
            parameters:
                target_probability: 0.65
    proso_feedback:
        domain: slepemapy.cz
        to: [slepemapy@googlegroups.com]
