default:
    proso_models:
        predictive_model:
            class: proso.models.prediction.PriorCurrentPredictiveModel
        option_selector:
            class: proso.models.option_selection.ConfusingOptionSelection
            parameters:
                allow_zero_options_restriction: true
    proso_flashcards:
        practice:
            common:
                set_length: 10
                fc_queue_size_max: 1
                fc_queue_size_min: 1
                save_answer_immediately: false
                cache_context: false
                queue_length: 10
    proso_feedback:
        domain: slepemapy.cz
        to: [slepemapy@googlegroups.com]
