default:
    proso_models:
        predictive_model:
            class: proso.models.prediction.PriorCurrentPredictiveModel
    proso_flashcards:
        practice:
            common:
                set_length: 10
            intro:
                set_length: 5
                fc_queue_size_max: 5
                fc_queue_size_min: 3
                save_answer_immediately: true

